<?php if ($this->pageCount): ?>
   <ul class="pagination pagination-sm">
    
   <!--Previous page llnk-->
    <?php if (isset($this->previous)): ?>
   <li class="active">
        <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>"> 
            << 
        </a>
   </li>
   <?php else: ?>
    <li class="disabled">
         <a href="#" onclick="return false;">
             <<  
         </a>
    </li>
    <?php endif; ?>
    
<!--Numbered page links-->
<?php foreach ($this->pagesInRange as $page): ?>
   <?php if ($page != $this->current): ?>
   <li>
      <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page;?>">
      <?php echo $page; ?>
      </a>
    </li>
<?php else: ?>
    <li class="active">
        <a href='#'><?php echo $page; ?></a>
    </li>
<?php endif; ?>
<?php endforeach; ?>
    
<!--    next page link-->
   <?php if (isset($this->next)):?>
      <li>
          <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>"> 
              >>
          </a>
      </li>
   <?php else: ?>
      <li class="disabled">
          <a href="#" onclick="return false;">
             >>
          </a>
      </li>
    <?php endif; ?>    
   </ul>
<?php endif; ?>