<div class="bs-docs-section">
    <div class="well">
<?php
$form->setAttribute('action', $this->url('admin/comment', array('action' => 'edit','id' => $id ))); 
$form->prepare();

echo $this->form()->openTag($form);
echo '<fieldset><legend>Редактировать комментарий</legend>';
echo '<div id="comment_errors"></div>';
echo '<div class="form-group">';    
echo '<label class="col-lg-2 control-label">Статья</label>';
echo "<div class='col-lg-10'>{$comment->getArticle()->getTitle()}</div>";
echo '</div>';

$e=$form->get('userMail');
$e->setLabelAttributes(array('class'=>'col-lg-2 control-label'));
echo '<div class="form-group">';    
echo $this->formLabel($e);
echo "<div class='col-lg-10'>{$this->formEmail($e)}</div>";
echo '</div>';

$e=$form->get('comment');
$e->setLabelAttributes(array('class'=>'col-lg-2 control-label'));
echo '<div class="form-group">';    
echo $this->formLabel($e);
echo "<div class='col-lg-10'>{$this->formTextArea($e)}</div>";
echo '</div>';

echo "<input type='hidden' value='{$comment->getId()}' name='id'>";
echo '<div class="form-group">';    
echo "<div class='col-lg-10'>";
echo $this->formRow($form->get('submit'));
echo '</div>';
echo '</div>';
echo '</fieldset>';
echo $this->form()->closeTag();    
?>
    
        
    </div>    
</div>

